var searchData=
[
  ['unaryconstructorclass',['UnaryConstructorClass',['../d0/d1b/classtesting_1_1gmock__generated__actions__test_1_1_unary_constructor_class.html',1,'testing::gmock_generated_actions_test']]],
  ['unaryfunctor',['UnaryFunctor',['../d7/d3d/structtesting_1_1gmock__generated__actions__test_1_1_unary_functor.html',1,'testing::gmock_generated_actions_test::UnaryFunctor'],['../de/ddc/structtesting_1_1gmock__more__actions__test_1_1_unary_functor.html',1,'testing::gmock_more_actions_test::UnaryFunctor']]],
  ['uncopyable',['Uncopyable',['../d7/da6/classtesting_1_1gmock__matchers__test_1_1_uncopyable.html',1,'testing::gmock_matchers_test']]],
  ['undefined',['Undefined',['../dd/d5f/structtesting_1_1gmock__matchers__test_1_1_undefined.html',1,'testing::gmock_matchers_test']]],
  ['union',['Union',['../dd/d8a/classscripts_1_1generator_1_1cpp_1_1ast_1_1_union.html',1,'scripts.generator.cpp.ast.Union'],['../d4/d94/classcpp_1_1ast_1_1_union.html',1,'cpp.ast.Union'],['../da/d94/classgoogletest-master_1_1googlemock_1_1scripts_1_1generator_1_1cpp_1_1ast_1_1_union.html',1,'googletest-master.googlemock.scripts.generator.cpp.ast.Union']]],
  ['unittest',['UnitTest',['../d7/d47/classtesting_1_1_unit_test.html',1,'testing']]],
  ['unittesthelper',['UnitTestHelper',['../df/dcf/classtesting_1_1internal_1_1_unit_test_helper.html',1,'testing::internal']]],
  ['unittestrecordpropertytesthelper',['UnitTestRecordPropertyTestHelper',['../d2/dab/classtesting_1_1internal_1_1_unit_test_record_property_test_helper.html',1,'testing::internal']]],
  ['universalprinter',['UniversalPrinter',['../d7/d76/classtesting_1_1internal_1_1_universal_printer.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_20_26_20_3e',['UniversalPrinter&lt; T &amp; &gt;',['../d2/d67/classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['universalprinter_3c_20t_5bn_5d_3e',['UniversalPrinter&lt; T[N]&gt;',['../d9/d6b/classtesting_1_1internal_1_1_universal_printer_3_01_t[_n]_4.html',1,'testing::internal']]],
  ['universalterseprinter',['UniversalTersePrinter',['../d6/d8f/classtesting_1_1internal_1_1_universal_terse_printer.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20char_20_2a_20_3e',['UniversalTersePrinter&lt; char * &gt;',['../d2/d0e/classtesting_1_1internal_1_1_universal_terse_printer_3_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20const_20char_20_2a_20_3e',['UniversalTersePrinter&lt; const char * &gt;',['../d3/ded/classtesting_1_1internal_1_1_universal_terse_printer_3_01const_01char_01_5_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_20_26_20_3e',['UniversalTersePrinter&lt; T &amp; &gt;',['../dd/dce/classtesting_1_1internal_1_1_universal_terse_printer_3_01_t_01_6_01_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20t_5bn_5d_3e',['UniversalTersePrinter&lt; T[N]&gt;',['../dc/d88/classtesting_1_1internal_1_1_universal_terse_printer_3_01_t[_n]_4.html',1,'testing::internal']]],
  ['universalterseprinter_3c_20wchar_5ft_20_2a_20_3e',['UniversalTersePrinter&lt; wchar_t * &gt;',['../d5/daf/classtesting_1_1internal_1_1_universal_terse_printer_3_01wchar__t_01_5_01_4.html',1,'testing::internal']]],
  ['unorderedelementsaretest',['UnorderedElementsAreTest',['../d9/d3e/classtesting_1_1gmock__matchers__test_1_1_unordered_elements_are_test.html',1,'testing::gmock_matchers_test']]],
  ['unprintable',['Unprintable',['../d6/da3/classtesting_1_1gmock__matchers__test_1_1_unprintable.html',1,'testing::gmock_matchers_test']]],
  ['unprintableinfoo',['UnprintableInFoo',['../d9/d6e/classfoo_1_1_unprintable_in_foo.html',1,'foo']]],
  ['unprintabletemplateinglobal',['UnprintableTemplateInGlobal',['../d8/d30/class_unprintable_template_in_global.html',1,'']]],
  ['unstreamable',['Unstreamable',['../d1/d57/class_unstreamable.html',1,'']]],
  ['using',['Using',['../df/d69/classscripts_1_1generator_1_1cpp_1_1ast_1_1_using.html',1,'scripts.generator.cpp.ast.Using'],['../d5/da0/classgoogletest-master_1_1googlemock_1_1scripts_1_1generator_1_1cpp_1_1ast_1_1_using.html',1,'googletest-master.googlemock.scripts.generator.cpp.ast.Using'],['../d8/d8e/classcpp_1_1ast_1_1_using.html',1,'cpp.ast.Using']]]
];
